# Use the official MySQL 8 image from Docker Hub
FROM mysql:8

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=1234567890
ENV MYSQL_DATABASE=db_service3
ENV MYSQL_USER=hoacode_service3
ENV MYSQL_PASSWORD=1234567890

# Copy custom MySQL configuration file
COPY ./mysql_custom.cnf /etc/mysql/conf.d/

# Expose port 3308 to the host
EXPOSE 3308
